name: Convert PieceCID v1 to v2 with height

on:
  workflow_dispatch:
    inputs:
      piece:
        required: true
        description: PieceCID of to convert
        type: string
      height:
        required: true
        description: Height of the Piece
        type: number

jobs:
  convertPieceCidV1ToV2WithHeight:
    name: Convert PieceCID v1 to v2 with height
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'pnpm'
      - name: Run job
        run: pnpm dlx @web3-storage/pieces v2 ${{ github.event.inputs.piece }} --height ${{ github.event.inputs.height }}
