

name: Get Aggregates pending deals

on:
  workflow_dispatch:

jobs:
  getAggregatesOffered:
    name: Get Aggregates pending deals
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Run job
        run: npm run get-aggregates-pending-deals -w packages/tools
