name: Get Aggregate deals

on:
  workflow_dispatch:
    inputs:
      piece:
        required: true
        description: PieceCID of the aggregate
        type: string

jobs:
  getDeals:
    name: Get Aggregate deals
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run job
        run: pnpm run get-aggregate-deals -w packages/tools ${{ github.event.inputs.piece }}