name: Stat Buffer

on:
  workflow_dispatch:
    inputs:
      buffer:
        required: true
        description: CID of the Buffer
        type: string

jobs:
  statBuffer:
    name: Stat Buffer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Run job
        run: npm run stat-buffer -w packages/tools ${{ github.event.inputs.buffer }}